package com.javarush.task.task04.task0419;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
import java.io.*;                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
import java.util.*;                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
public class Solution {                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    public static void main(String[] args) throws Exception {                                                                                                                                                                                                                                                                                                                                                                      //напишите тут ваш код                                                                                                                                                                                                                                                                                                                                                                                                                  
          BufferedReader br=new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                                                                                                                                                                                                                                
          int result=Integer.parseInt(br.readLine()), inInt;                                                                                                    
          for (int i=0;i<3;i++){                                                                                                    
             inInt = Integer.parseInt(br.readLine());                                                                                                    
             if (result<=inInt){result=inInt;}                                                                                                    
          }                                                                                                    
          System.out.println(result);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}